name: Update README with Most Active Day Badge

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch GitHub Events and Determine Most Active Day
        id: fetch_active_day
        run: |
          events=$(curl -s "https://api.github.com/users/${{ github.repository_owner }}/events/public")
          days=$(echo "$events" | jq -r '.[].created_at' | cut -d'T' -f1)
          weekdays=$(echo "$days" | xargs -I{} date -d {} +%A)
          most_active_day=$(echo "$weekdays" | sort | uniq -c | sort -nr | head -n1 | awk '{print $2}')
          echo "MOST_ACTIVE_DAY=$most_active_day" >> $GITHUB_ENV

      - name: Update README with Badge
        run: |
          badge_url="https://img.shields.io/badge/Most%20Active%20Day-${MOST_ACTIVE_DAY}-blue?style=flat-square"
          sed -i '/<!-- START_BADGE -->/,/<!-- END_BADGE -->/c\<!-- START_BADGE -->\n![]('"$badge_url"')\n<!-- END_BADGE -->' README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update most active day badge" || echo "No changes"
          git push
